name: Bug Report
description: Help us improve Fredy by reporting a bug
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug.
      placeholder: e.g. "Fredy crashes when I click on Save."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "It should save without errors."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Fredy crashed with error XYZ."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: Add screenshots or paste log output to help explain the problem.
      placeholder: "Drag and drop screenshots here, or paste logs."
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: "OS: macOS 15, Browser: Chrome 124, App version: 1.2.3"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Any other information that might help..."
    validations:
      required: false
