---
name: Feature Request
about: Suggest an improvement or new idea for this project
title: "[Feature]: "
labels: enhancement
assignees: ''
---

## Related Problem
Is your feature request related to a problem? Please describe clearly.  
Example: "I'm always frustrated when [...]"

## Proposed Solution
Describe the solution or feature you’d like to see implemented.

## Alternatives Considered
List any alternative solutions or workarounds you’ve tried or thought about.

## Benefits
Explain how this feature would improve the project or user experience.

## Additional Context
Add any other context, examples, or screenshots that might help clarify your idea.
